CREATE PROCEDURE ADMSUP.AT_GET_PROJECT_INFO
  @IN_PROJECT NVARCHAR(500) = '',
  @ALL_USERS INT = 0
AS 
/*INTERNAL*/
  SELECT AWP.WWP_PROJECT AS PROJECT,
         AWP.WWP_OBJECT AS "OBJECT",
         AWP.WWP_NAME AS "OBJECT_NAME",
         AWP.WWP_USER AS "USER_NAME",
         AWP.WWP_CODE_TEXT AS "CODE_TEXT",
         AWP.WWP_CREATED AS "CREATION_DATE"
  FROM AT_WORKING_PROCESS AWP
  WHERE UPPER(AWP.WWP_PROJECT) LIKE UPPER('%'+@IN_PROJECT+'%') OR @IN_PROJECT IS NULL
  AND (AWP.WWP_USER = (select  CURRENT_USER) OR @ALL_USERS = 1)
RETURN
GO
